# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Peek Challenge' do

pod 'Fabric'
pod 'TwitterKit'

end

target 'Peek ChallengeTests' do

end

target 'Peek ChallengeUITests' do

end

